name: Sonar Scan
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y libpcap0.8 libpcap-dev \
          && wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip \
          && unzip build-wrapper-linux-x86.zip \
          && ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw_output make \
          && ls bw_output && cat bw_output/build-wrapper-dump.json \
          && echo "========" && cat bw_output/build-wrapper.log
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
